### PR TITLE
raise CBA event on showing passport

### PR DESCRIPTION
**Pull request by nomisum**
allows hooking in other modules

### CODE REVIEW

**Comment by McDiod** [comment]
fn_showPassport or fn_receiveShowPassport might be better suited. Will investigate tomorrow.

**Comment by McDiod** [comment]
Okay so there are three different modes a passport might be viewed.

1. unit showing their passport to other unit
  1.1 other unit looks at the passport
  1.2 other unit is busy and can't look at the passport
2. unit checking the passport of a dead, surrendered or captive unit
3. unit checking own passport

Which of these do you need the event for?

**Comment by nomisum** [comment]
1.1

Use case: AI checks passport on borderCrossing, needs to decide what to do.
https://github.com/gruppe-adler/a_st_borderCrossing.VR/blob/master/grad-borderCrossing/functions/fn_init.sqf#L3

**Comment by McDiod** [comment]
I guess it's the right function then, because it's the only one that actually knows whether the target is looking at the passport or not.

However it's not only executed whenever a unit shows their passport, but also when the recipient is busy or stops looking at the passport (function updates dialog below). So I'd call the event `showStateChanged` or something. User can then check the `_state` param to determine what is happening (0 == target is looking at passport).

**Comment by McDiod** [comment]
renamed it

**Pull request merged**
